### ISSUE TITLE
[Bug]: Bow breaking things

### ISSUE THREAD

**Issue by ootorikagerou** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#103]
### Which mod is this report for:

Buffer

### Describe the bug

When I equip the bow, it gets stuck on the loading screen.
If I remove the Buffer from the mod, it works s fine.
Also, in version 2.24, if you equip a bow
no longer have access to the blacksmith, item boxes, etc.

**Comment by Bimmr** [comment]
Are both of those issues on 2.24?

**Comment by Bimmr** [comment]
I just tested with a bow, and everything is working for me. Try using only REFramework and Buffer as the only mods.

**Comment by ootorikagerou** [comment]
Sure, if you start with just a baffer.
It worked fine.
Perhaps there is a conflict with another mod.
I was not able to pin down what that mod was.
Sorry for my poor English.

**Comment by ootorikagerou** [comment]
I think the old mods are suspect.
