### ISSUE TITLE
[Feature]: Super Armor

### ISSUE THREAD

**Issue by HasturQ** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#104]
### Which mod is this report for:

Buffer

### Is your feature request related to a problem? Please describe.

May you add "Super Armor"? Perhaps just like "Hyper Armor", playerBase:set_field("_SuperArmorTimer", 500)?

And a Bug report, 
In config.json, "heavy_bowgun" seems not to record "counter_charger".

Best Regards.

### Describe the solution you'd like

```
        if data.super_armor then
            playerBase:set_field("_SuperArmorTimer", 500)
        end
```

**Comment by Bimmr** [comment]
What is the difference between Hyper and Super Armor?

**Comment by Bimmr** [comment]
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/5646b318a2784399b757fc8816e1e2266d13a41a Fixes counter charger not saving

**Comment by HasturQ** [comment]
> What is the difference between Hyper and Super Armor?

According to [this](https://www.reddit.com/r/MonsterHunterMeta/comments/104k9zm/super_armor_x_hyper_armor_differences/), super armor is MHRise is Flinch Free III + Windproof. 
Hyper Armor is Prevents flinching and knockback when attacked.

According to [this mod](https://www.nexusmods.com/monsterhunterrise/mods/980), we can confirm the existence of "_SuperArmorTimer".

**Comment by Bimmr** [comment]
Added https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/ea59613feb155b191e33a69bbc5b62868da53bc0
