### ISSUE TITLE
[Bug]: Still die with Health Mods and or Hyper Armour  

### ISSUE THREAD

**Issue by Neonliy** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#108]
### Which mod is this report for:

Buffer

### Describe the bug

I'm experiencing issues with the health and armour mods Despite applying these modifications, my character still dies during gameplay. I'm not sure if there's a bug in the game or if I'm not applying the modifications correctly.

 Can you provide any suggestions on how I can properly apply the health and armor modifications to ensure they work as intended? I'm wondering if it would be best to max out my defense every hunt instead of relying on the modifications.

I appreciate any advice or insights you can provide to help me solve this problem. Thank you.

**Comment by Neonliy** [comment]
Am using gamepass version of mod 
Have tried reinstalling reframework and buffer

**Comment by Bimmr** [comment]
It's not god mode. If you take more damage than your health and armour can
handle you will die.

**Comment by Neonliy** [comment]
got it thanks for clarifying
