### ISSUE TITLE
[Feature]: Support Vortex deployment

### ISSUE THREAD

**Issue by zxeoc** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#109]
### Which mod is this report for:

Buffer

### Is your feature request related to a problem? Please describe.

When deploy Buffer with Vortex mod manager, it will not work. I saw the error message "Buffer:\nUnable to load Language files...". It seems it's because Vortex deploy files as symlinks, and "fs.glob([[Buffer\\Languages\\.*json]])" in language.load_languages() can't read them as real files. Is there a way lua code can deal with symlinks?

### Describe the solution you'd like

Buffer can load symlinks as well as real files.

**Comment by Bimmr** [comment]
Doesn't look like Reframework supports files outside of its folder.
https://cursey.github.io/reframework-book/api/fs.html

**Comment by zxeoc** [comment]
It's strange, because I saw another API (json.load_file(filepath)) works fine with symlinks. I'll check the issues of REFramework.

**Comment by praydog** [comment]
Latest REF supports symlinks now for fs.glob
