### ISSUE TITLE
Add Sword & Shield

### ISSUE THREAD

**Issue by Bimmr** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#11]
# Is your feature request related to a problem? Please describe.
Add sWord & Shield stuff

# Describe the solution you'd like
[Switch Skill - Destroyer Oil](https://monsterhunterrise.wiki.fextralife.com/Destroyer+Oil)

# Additional context
I remember seeing some things in the PlayerData about oil

**Comment by saltedchip** [comment]
idk how this works but basicly apply once and stays forever, just like what you did with the bow buff.

**Comment by Bimmr** [comment]
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/0614b10f8e4bb27433b553fa5965cf5b6ee07677
