### ISSUE TITLE
[Bug]: Math not found

### ISSUE THREAD

**Issue by typicalblisse** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#112]
### Which mod is this report for:

Buffer

### Describe the bug

when using the buffer GUI menu and trying to edit the character stats (i.e.- attack, affinity, defense, and elemental damage I only see changes on all except the attack defense when I look in the status tab of the game I have tried to fix of using any ig or swiping the switch to the left and nothing seems to work/. Buffer is the only mod I use. 

![Screenshot 2023-09-07 205851](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/assets/144572851/f545cb4f-061a-43c4-83de-a03465db428c)

**Comment by Bimmr** [comment]
What version of REFramework are you using because it's trying to say that it can't use the Math library.
