### ISSUE TITLE
[Bug]: "Element" setting affect Buddies 

### ISSUE THREAD

**Issue by ChilledArachnid** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#113]
### Which mod is this report for:

Buffer

### Describe the bug

When you put any value under the "Element" section, whatever is put in also overwrites the element type and amount of both of your buddy's weapons, no matter what type of element is actually on the weapon you equip them with. Is there any way that you can make this not happen, as it is useful to keep status elements on buddies while your own character has a specific element. Thank you.  
I've attached a picture demonstrating it, every buddy weapon shows as having fire element. 

![Screenshot 2023-11-13 213712](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/assets/150770848/c2ef6258-2bb8-447b-aee6-dfc211e96536)

**Comment by Bimmr** [comment]
If I'm being honest I was kinda hoping you wouldn't create the ticket so I could just ignore it lol. But since you made the ticket I'll take a look and see if I can fix it.

**Comment by Bimmr** [comment]
So far I haven't had luck with finding an alternate way to modify the stats that doesn't affect both. It could be because it's been a few months since I played with a REFramework mod. I'll give it another go this weekend but I'm not sure if it's something I'm going to be able to fix.

**Comment by Bimmr** [comment]
Doesn't look like I'm going to be able to get it to work with the way I'm doing it at the moment. Due to no longer playing the game myself, I don't think I'm going to be trying to change the way I do this. Sorry.
