### ISSUE TITLE
[Bug]: show all dango

### ISSUE THREAD

**Issue by skh186** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#114]
### Which mod is this report for:

Buffer

### Describe the bug

show all dango Cannot close,When eating dango my MHR keep crashing

**Comment by Bimmr** [comment]
The show all dango is a bit buggy with the way it works. Honestly, I'd say to not use it, but instead use https://www.nexusmods.com/monsterhunterrise/mods/1432
