### ISSUE TITLE
[Bug]: Dialog pups up when starting the game

### ISSUE THREAD

**Issue by johnazre** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#115]
### Which mod is this report for:

Buffer

### Describe the bug

There's a dialog that pops up that when the game is loading saying:

Last Script Error: sol: runtime error: error loading module 'Buffer.Misc.Bindings' from file "....../Buffer\Misc\Bindings.lua"

If I close the dialog box, the game seems to start fine. Not sure if the this breaks the buffer, though.

**Comment by Bimmr** [comment]
What version of Buffer and ReFramework? And is there any more to the error? Normally it will say why it can't load it.

**Comment by johnazre** [comment]
Buffer: v2.22
ReFramework: v1.617

Tested it and verified that it is not blocking the buffer from working. It was working fine for a while. It MIGHT be the new nightly build for reframework, but I'll test that out and verify.

**Comment by johnazre** [comment]
![image](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/assets/11783363/c7787d46-0c0c-43f1-87e0-319a9672fa6f)

**Comment by johnazre** [comment]
Were you able to replicate this? I've tried a few different versions of ReFramework to see if that changed anything, but I couldn't identify anything.

**Comment by johnazre** [comment]
Ok, so I did a little digging and I got the dialog box to go away. Apparently my Bindings.lua file in the Misc directory got encrypted or something and it was a weird string of letters/numbers/characters and nothing else. I re-downloaded the buffer mod and replaced that file and that fixed the dialog box, but I wasn't able confirm that everything else was working. Just a heads up.

**Comment by johnazre** [comment]
Nevermind. I made a few value changes in the lua files and confirmed it works. All good now. Closing the issue.
