### ISSUE TITLE
[Bug]: i got this problem when use heroics

### ISSUE THREAD

**Issue by hoanglongf20** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#116]
### Which mod is this report for:

Buffer

### Describe the bug
i download buffer from nexus v2.22
i copy this error from re2_framework_log

[2024-05-14 18:54:08.992] [REFramework] [error] sol: runtime error: ...er Rise\reframework\autorun/Buffer\Modules\Character.lua:137: attempt to index a nil value (global 'Math')
stack traceback:
	...er Rise\reframework\autorun/Buffer\Modules\Character.lua:137: in function <...er Rise\reframework\autorun/Buffer\Modules\Character.lua:69>

**Comment by Bimmr** [comment]
Ah, I guess that was something I had fixed in the GitHub version but not
the released version.
