### ISSUE TITLE
[Bug]: Games refuses to load, hanging before splash art

### ISSUE THREAD

**Issue by Reny900** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#117]
### Which mod is this report for:

Buffer

### Describe the bug

I've upgraded from Buffer 2.2 to 2.4 and stumbled upon this error. This keeps happening and its actively preventing me to load MH rise at all while version 2.4 is installed. Being afraid i had made some mistakes during the copy paste process of the upgrade script (lol) i went back and deleted 1-by-1 every file/folder from Buffer, and installed them again.
Which only lead to the same result.

### Additional context

![image](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/assets/19189602/6c2d89da-0c24-451a-a429-865604a7a244)
This is currently the moment the game froze, that stuff is MSI afterburner and RTSS OSD monitoring stuff

**Comment by Bimmr** [comment]
Any chance this is the same issue?

When I test the mod I test it with no other mods.
![image](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/assets/5053870/9e0f8056-3744-4532-913d-7fa74a4c28fc)

**Comment by Reny900** [comment]
I don't think i know what mods he is referring to, to be honest.
