### ISSUE TITLE
[Feature]: Dragonheart while regenerating HP (Kushala Bless/SuperRecDango)

### ISSUE THREAD

**Issue by Shonsho** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#120]
### Which mod is this report for:

Buffer

### Is your feature request related to a problem? Please describe.

When building kushala blessing 3 or eating the super health recovery dango it keeps activating and deactivating the dragonheart skill.

### Describe the solution you'd like

Maybe add an option where the new max HP goes just a bit lower?

**Comment by Bimmr** [comment]
Unable to test since I don't have the game installed anymore - but should fix the issue
