### ISSUE TITLE
new 'auto-consumable' section

### ISSUE THREAD

**Issue by dracahn** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#13]
# Is your feature request related to a problem? Please describe.
At the beginning of a hunt, I end up spamming the same 3 foods
Mid hunt - every time a monster transitions between areas, I spam the same few consumables
It would be nice if these were auto-applied or easily applied.

# Describe the solution you'd like
Add a new section to the buffer app - maybe under character
The new section should contain a list of items with a slider next to them.  The slider should have 3 options:
- Off
- Start Hunt
- Start Combat
- Always

For each item in the 'Off' state: do nothing
For each item in the 'Start Hunt' state: Apply the buff a single time at the start of the hunt (or on death/respawn)
For each item in the 'Start Combat' state: Apply the buff each time the player goes from 'out of combat' to 'in combat'.
For each item in the 'Always' state: Every few seconds, refresh the items/buff

Items to add to the list:
Whetstone (set sharpness to max and trigger protective polish)
Demon Drug
Mega Demon Drug
Demon Powder
Might Seed
Might Pill
Armorskin
Mega Armorskin
Hardshell Powder
Adamant Seed
Adamant Pill
Dash Juice
Immunizer
Gourmet Fish
Ration

# Additional context
I might have forgotten about some additional consumables - if you think of any more feel free to add them.
Personally I don't care about the 'Always' state.  Someone else will probably want it though.
Also, don't worry about conflicts.  E.G. someone has Mega Demon Drug and Demon Drug set to 'always'. If people create their own conflicts, let me solve it themselves.

optional: consume/use items from your inventory any time one of these is triggered (excluding the always state)

**Comment by Bimmr** [comment]
I feel like this would work better as a separate mod as that is more of a quality of life and not as cheaty as the buffer mod.

I do like the idea though so I may make something like that when I get time.

**Comment by Bimmr** [comment]
Going to close this ticket as the mod AutoBuff seems to do this, and there's no point in re-inventing the wheel.
