### ISSUE TITLE
Slider for the Sharpness value

### ISSUE THREAD

**Issue by RamenNoodles** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#15]
Bludgeoner skill offers 10% more damage at green or lower sharpness, currently I'm manually editing the value in the code. 

I'd like to see Sharpness having it's own dropdown with a slider to adjust the value to get different levels of sharpness.  Unfortunately each weapon has a different value to determine its level so I can only see it being a slider.

**Comment by RamenNoodles** [comment]
Just checked out the update and saw that you can get the sharpness levels without being weird with big numbers. Though a slider would still be nice to change it on the fly.

**Comment by Bimmr** [comment]
I was actually considering making it a slider, I just wasn't sure if it
would get used. I can change it to a sharpness slider in the next version.

**Comment by Bimmr** [comment]
Adde in latest version: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/c2d93d3e76559b68590a6fcfb747838e1e06da5a
