### ISSUE TITLE
Unlimited Health Causes Instant Death Moves

### ISSUE THREAD

**Issue by Corus86** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#20]
Not sure why it does so, but when you use unlimited health, some bosses' moves will instant kill you even when they wouldn't do so normally. Magnamalo and Teostra do this, they'll hit you with an attack that inflicts burn or blight and you'll instantly die from that attack.

**Comment by Bimmr** [comment]
I wasn't able to replicate this the other day, and even if I can I'm not sure there's anything I can do as all the code is doing is setting your health to your max health every update. 

I do have an idea of checking if the max health is higher than the current health before setting it, but I'm not 100% that would solve the issue.

**Comment by Corus86** [comment]
Oh I found out what it is, it was because my defense was too low and I had a very large negative resistance. Essentially the boss did more damage than my HP bar and insta killed me. The fix was to enable defense mod as well as the unlimited health.
