### ISSUE TITLE
Toggle for Status Effects, Elemental Blights & Abnormal Status Ailments on the player

### ISSUE THREAD

**Issue by MiguelAlen** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#23]
As said, an option to trigger for example poison on the player, or the mizutsune bubbles and make the hunts a bit more challenging.
 It would also help trigger  coalescence, dragonheart and some ofensive high risk high reward skills.
Anyway, thanks for your job!

**Comment by Bimmr** [comment]
I'll see what I can do, no promises though

**Comment by MiguelAlen** [comment]
No worries, just a thought. Still, thanks for the effort made.

**Comment by Bimmr** [comment]
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/bf6178027238b723e9fe696e5442f2f4cf313806
Added options for Dragonheart, Heroics, and Adrenaline. Currently working on ways to control blights

**Comment by MiguelAlen** [comment]
You're too much! Your work is great, thanks for your effort.

**Comment by Bimmr** [comment]
Added ways to prevent conditions and status effects: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/d079ff3165f68749699d88d0760d9f5a176533c5

Haven't figured out how I want it formatted just yet to allow for applying a condition

**Comment by MiguelAlen** [comment]
Didn't notice at first, seems health is no longer decreasing when you are hit, at all skill levels for dragonheart. 
Will test "Added ways to prevent conditions" tomorrow. Still, a lot of thanks for your work.

**Comment by Bimmr** [comment]
Just updated it to limit your health instead of setting your health https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/04748741caa5617f69d143120cc3d6e657fc1097

**Comment by Bimmr** [comment]
Uploaded to Nexus: https://www.nexusmods.com/monsterhunterrise/mods/685?tab=files
