### ISSUE TITLE
Toggleable/Slider Skills

### ISSUE THREAD

**Issue by Ryzx6** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#25]
There's a lot of skills that pretty much no one use so if you can add it would be nice

Evade Window/Extender
Partbreaker
Flinch Free
Speed Eating
Earplugs
Ailment Resistance
etc.

Just to give you idea

**Comment by Bimmr** [comment]
I'll take a look into preventing ailments/conditions but the rest aren't things that I'm likely to add

**Comment by Bimmr** [comment]
The remaining ailment/condition resistance is a close enough duplicate of https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/issues/23 that I'm going to close this ticket.
