### ISSUE TITLE
Permanent I-Frames 

### ISSUE THREAD

**Issue by Corus86** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#26]
Related to previous insta kill issue, if there's a large enough attack you can die with unlimited health + defense modifier.
I doubt there's any attacks that can one shot you if you max out the defense multiplier (Lvl 3100), but this would prevent that and allow you to essentially not take knockdowns I think.

My proposed solution is to force the player to always be in a "dodge"/I-frame state. This would essentially save you from any attacks regardless of strength and prevent knockdowns since the attack won't affect player in I-frames.

**Comment by Bimmr** [comment]
Sorry, this falls into the same category of making skills always active. It's not something I'm interested in doing as it's too cheaty for my taste.
