### ISSUE TITLE
it is possible to change skill Partbreaker?

### ISSUE THREAD

**Issue by wei027171** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#28]
# Is your feature request related to a problem? Please describe.
Partbreaker Lv3 give 30% part damage Increase 
but I'm still having trouble getting the tail cut off
# Describe the solution you'd like
increase to 50% or 100%    and a cheat button can easily break any where 
# Additional context

**Comment by wei027171** [comment]
or don't even need skills Partbreaker

**Comment by Bimmr** [comment]
Sorry but this isn't something I'm able to do. 

With buffer I'm trying to keep it so all in doing is activating or deactivating things that the pleasure already has. That way I don't have to redo things such as damage controllers for either the player or monster
