### ISSUE TITLE
Dragonheart threshold not working

### ISSUE THREAD

**Issue by MiguelAlen** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#29]
First of all, I guess what you are doing is to limit player hp bar to the point where those skills are activated, which is a wonderful solution instead of making them stronger by being activated without hp reduced.
Heroics and Adrenaline toggle to limit hp work perfectly fine but dragonheart no. Can't figure why, tryed in solo and with 250, 150 and 100 hp.
If I were to know wheres the issue I'll edit the post.
Again, thanks.

**Comment by Bimmr** [comment]
I actually forgot to test those before pushing the update. Glad to know that the other 2 work. I'll take a look at the Dragonheart one

**Comment by MiguelAlen** [comment]
Perfect, I'll test it again once it is updated, until now couldn't make dragonheart work so I guess it is not an ocasional bug. Have a good day

**Comment by Bimmr** [comment]
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/2f0913e7bb0b8b01263aff65420d39a5be012ad8 Dragonheart should be fixed if you're able to test. I only had the resources to test at Dragonheart lvl 3

**Comment by MiguelAlen** [comment]
I tested all levels of dragonhearth and works as intended. Wonderful job and thanks a lot!

**Comment by Bimmr** [comment]
Perfect. I'll upload it to Nexus in a bit.
