### ISSUE TITLE
How to I change the menu size

### ISSUE THREAD

**Issue by WolfyKaslana1234** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#31]
![image](https://user-images.githubusercontent.com/99475536/180593869-ba3e7293-9d24-4087-bb91-914cbe8f21b2.png)
 Its always look like this everytime i start up the mod
 How do i adjust it ?

**Comment by port-eighty** [comment]
drag the lower left corner

**Comment by WolfyKaslana1234** [comment]
Thanks.
