### ISSUE TITLE
the gunlance unlimited dragoncannon not work

### ISSUE THREAD

**Issue by GodBlessYooo** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#32]
# Describe the bug
![image](https://user-images.githubusercontent.com/109603892/180600319-564d5ea9-9785-4b72-bfd8-cda5ea3aad73.png)
it is still in cool down

**Comment by Bimmr** [comment]
Fixed: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/33ff6b55bbe8da39006721f98f9108e95f95be7d

Found a few other buffs that were broken because of the same issue. I'll be uploading to nexus in just a few minutes

**Comment by GodBlessYooo** [comment]
thanks, again  :D
