### ISSUE TITLE
Affinity buffer request

### ISSUE THREAD

**Issue by Naekou** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#33]
# Not really related to a problem, just wondering if it's possible to add in since we already have atk/def sliders

# Affinity slider to buff character similar to atk/def. Maybe something similar to the fling trainer but more permanent.

# Additional context

![Screenshot 2022-07-23 195507](https://user-images.githubusercontent.com/109856514/180603800-aba13e4b-26f1-4338-8978-a45f530f4bbd.png)

**Comment by Bimmr** [comment]
I've tried looking into editing affinity, but all I could find was a buff that gave bows +50%. When I'm able to find a nicer way of editing attack and defense I should be able to also add in affinity. No ETA on this feature at the moment.

**Comment by Bimmr** [comment]
Added https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/2ac2076729055dc5638a55b8ed83d7e904b66b6c
