### ISSUE TITLE
Stuck on loading screen when equip with Bow

### ISSUE THREAD

**Issue by jetpackgo** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#34]
i got a freeze on loading screen when i equip Bow 
- i start notice it when i do arena with bow when i jump into quest it freeze at load screen
- i try equip my bow load out and try doing Normal MR Quest it also Freeze
- and if u equiped bow and choose your save file and load in to village it freeze too
- i happen from your mod because i check it out already by remove other mod and singly put only 1 mod in one by one

**Comment by Bimmr** [comment]
Which bow are you using?

**Comment by jetpackgo** [comment]
- any bow can trigger freeze screen
- infinite bow coating , bowgun ammo and infinite eating item
- ig buff and Switchaxe infinte phial

**Comment by Bimmr** [comment]
Are you online or playing solo?

**Comment by jetpackgo** [comment]
First time i play mr arena 2 with my friends and freeze
After that i try solo on the same arena quest and still freeze

So i equip anjanant bow and go on normal MR quest and freeze too

**Comment by Bimmr** [comment]
I'll give it a try with that bow and the same mods enabled in a bit

**Comment by Bimmr** [comment]
So I'm able to load into a mission with my Daimyo warbow+ and no armour equipped with all the same buffs enabled without it freezing/crashing.

**Comment by Bimmr** [comment]
I seem unable to replicate the freeze/crash Using the following loadout and the following buffs enabled:
![image](https://user-images.githubusercontent.com/5053870/180661556-047721b3-7e63-4299-8591-501fb13da21d.png)
![image](https://user-images.githubusercontent.com/5053870/180661565-4ac2bade-8cde-4f17-9141-a191854d75df.png)
![image](https://user-images.githubusercontent.com/5053870/180661574-551289b1-7608-4ec6-a48f-003db67a820c.png)

**Comment by Adeylis** [comment]
Hello, I'm also having the bow freeze issue here's what I currently run
![freeze](https://user-images.githubusercontent.com/109923599/180665883-0e076bc6-30ce-45fe-82f5-0aa6e3bf2dc1.PNG)

I turned off everything from your mod's end. Currently the only thing active is Fast returns, Inf consumbles Reframework, the new Seconds please Dango mod, Buddy skill editor.
I also have Fluffy mods majority of them are Armor mods but I do have Item duration Das- seed- powder- immunizer-gourmet for 50min, enhanced petalace, unerf slice, unerf sticky ammo,and moving shot and reload. although these should only affect Bowguns but by chance this should interfere with bows  idk.
I'm also using the chamelos bow

**Comment by Adeylis** [comment]
Just deactivated all of Infinite consumble reframework,  deleted and reinstalled your mod, I still freeze crash. I'm not sure what is interfering with your mod.

**Comment by Bimmr** [comment]
What other mods do you have?

**Comment by Bimmr** [comment]
What version of REFramework are you using?

**Comment by Adeylis** [comment]
Currently using the reframework from nexus thats up to date.
![Mod1](https://user-images.githubusercontent.com/109923599/180667375-04d7c901-f456-40b6-88d9-392d0ddbe4ef.PNG)
![mod2](https://user-images.githubusercontent.com/109923599/180667376-a5aa1b46-a23f-40b5-95f1-59179bba36d5.PNG)
These are the mods I have active on FluffyManager
As stated in the previous post a majority of them are Armor mods. If you need more details on the armor mods let me know.
![mod3](https://user-images.githubusercontent.com/109923599/180667430-3dcb87b8-8865-4346-9c40-a503e0b31163.PNG)
Here are the Lua files in my REframework Autorun Folder. Other mods not shown here are RiseCharm Editor and Reframework d2d which are in my plugins.

**Comment by Adeylis** [comment]
I don't have any mods that .Pak files either if that helps

**Comment by Adeylis** [comment]
I will say, when running into this bow problem yesterday. i did a clean uninstall of all fluffy mods and I would still freeze upon loading with a bow. So If I had to narrow it down it has to be something Reframework related?

**Comment by Bimmr** [comment]
If you open the Script Runner header in REFramework and spawn the debug console, does it say anything when before it freezes?

I'm currently testing with the REFramework version they have on their Nightly releases: https://github.com/praydog/REFramework-nightly/releases last updated 5 hours ago

**Comment by Adeylis** [comment]
> If you open the Script Runner header in REFramework and spawn the debug console, does it say anything when before it freezes?
> 
> I'm currently testing with the REFramework version they have on their Nightly releases: https://github.com/praydog/REFramework-nightly/releases last updated 5 hours ago
I forgot to get the debug as i was loading in the quest but here is what i got during the scriptrunner
![Scriptrunner](https://user-images.githubusercontent.com/109923599/180668144-a2766d12-8b17-4d4f-a1e6-6ae615665452.PNG)
![Error log](https://user-images.githubusercontent.com/109923599/180668150-2356186c-0175-40c4-a68a-db3b7535440e.PNG)
Here's the error log when trying to load back in with my character with the bow

**Comment by Adeylis** [comment]
I'm also using the new nightly build you linked and I'm still getting the problem.

**Comment by Bimmr** [comment]
Can you try attaching your autorun folder as a .zip here so I can give that a try?

**Comment by Adeylis** [comment]
[autorun.zip](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/files/9177061/autorun.zip)
Here you go hope this helps

**Comment by Bimmr** [comment]
So far from my testing, it looks like having this mod and buffer is causing the freeze- not sure why yet:
mhrise_edit_sharpness.lua

**Comment by Adeylis** [comment]
I see, it's a relatively new mod I think? it's this mod https://www.nexusmods.com/monsterhunterrise/mods/576?tab=description

**Comment by Adeylis** [comment]
Removing that lua file did solve the loading problem, thanks. Although I'm not sure if people have the same mods as me giving them the same issue.

**Comment by Bimmr** [comment]
@jetpackgo Are you able to confirm if you also have the **_mhrise_edit_sharpness.lua_** reframework mod installed? And if not could you please send me a zip of your autorun folder so I can do some testing?

**Comment by jetpackgo** [comment]
yep i also have that .lua

**Comment by Bimmr** [comment]
If you remove that mod, the buffer mod should no longer crash with bows. Tomorrow I'll try playing around and see if I can figure out why

**Comment by Bimmr** [comment]
Moving this ticket over to https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/issues/36 so I can track broken mods and see if I can solve the issue

**Comment by jetpackgo** [comment]
but sharpness .lua is more detail that Buff.lua sharpness  im feel sad now

**Comment by Bimmr** [comment]
@jetpackgo 
If you download from the release here on GitHub it should no longer crash/freeze your game

**Comment by Bimmr** [comment]
And what version of REFramework?
