### ISSUE TITLE
Crash/Freeze

### ISSUE THREAD

**Issue by Bimmr** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#36]
# Describe the bug
Other mods that are hooking the PlayerManager Update when used with buffer are causing the game to freeze on loading after choosing a character when the current loadout contains a bow or on quest load if changed to a bow after loading character,

# Additional context
Mods that are confirmed to be an issue:
- [Edit Sharpness](https://www.nexusmods.com/monsterhunterrise/mods/576)
- [Infinite(or skill's border)HP](https://www.nexusmods.com/monsterhunterrise/mods/201): 
- [Infinite Stamina](https://www.nexusmods.com/monsterhunterrise/mods/200)

**Comment by Bimmr** [comment]
I've confirmed that it seems related to how I'm removing deviation from bow guns.

**Comment by Bimmr** [comment]
Should be fixed https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/5634fd31f6858b0121e33db3c4d85330fec6226b

If you want to test you can download from releases

**Comment by Adeylis** [comment]
So, the issue with bow is now fixed?
