### ISSUE TITLE
RE framework buffer runtime error

### ISSUE THREAD

**Issue by Gr1mmCrypt** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#38]
When ever REframework tries to initialize buffer it populates this runtime error. 

sol: runtime error: ...\common\MonsterHunterRise\reframework\autorun\Buffer.lua:4: module 'Buffer Modules.Utils' not found:
        no field package.preload['Buffer Modules.Utils']
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\lua\Buffer Modules\Utils.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\lua\Buffer Modules\Utils\init.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\Buffer Modules\Utils.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\Buffer Modules\Utils\init.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\..\share\lua\5.4\Buffer Modules\Utils.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\..\share\lua\5.4\Buffer Modules\Utils\init.lua'
        no file '.\Buffer Modules\Utils.lua'
        no file '.\Buffer Modules\Utils\init.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\reframework\autorun/Buffer Modules\Utils.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\reframework\autorun/Buffer Modules\Utils/init.lua'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\reframework\autorun/Buffer Modules\Utils.dll'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\Buffer Modules\Utils.dll'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\..\lib\lua\5.4\Buffer Modules\Utils.dll'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\loadall.dll'
        no file '.\Buffer Modules\Utils.dll'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\Buffer Modules.dll'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\..\lib\lua\5.4\Buffer Modules.dll'
        no file 'c:\program files (x86)\steam\steamapps\common\MonsterHunterRise\loadall.dll'
        no file '.\Buffer Modules.dll'
stack traceback:
        [C]: in function 'base.require'
        ...\common\MonsterHunterRise\reframework\autorun\Buffer.lua:4: in main chunk

Could it be REFramwork? Any suggestions?

**Comment by Bimmr** [comment]
Looks like it's missing the Buffer Modules folder

**Comment by Gr1mmCrypt** [comment]
I thought that at first too, and that when I used Vortex to install and manage the folders it deleted the Buffer Modules folder. It still wont work. What are of the game files should I put it, so I can try it without going through the Vortex Manager?

**Comment by Bimmr** [comment]
Apparently Vortex has issues installing the mod. Someone on the mod page
said

''''
23 July 2022, 1:39PM
I noticed a problem with version 2.03 when installing the mod with Votex.
Vortex pushes all files into a single "autorun" folder and deletes the
"Buffer Modules" folder.

So you have to go to "Open in File Manager" in Vortex, for the "Buffer"
mod, and manually create a "Buffer Modules" folder. Then all files except
"buffer.lua" must go into it.

After that everything should work fine
''''

**Comment by Gr1mmCrypt** [comment]
I've already done that and got the same error. Both inside and outside the autorun folder.

**Comment by Bimmr** [comment]
Can you post screenshots of the REFramework folder, the autorun folder, and
the Buffer Modules folder?

**Comment by Gr1mmCrypt** [comment]
Okay, I'm blind. There is a second 'autorun' folder you have to take care of as well. Now I'm just getting this.
![image](https://user-images.githubusercontent.com/109995024/180891147-4be1bd36-c15f-40cf-a3ca-ac799ee6eb94.png)

**Comment by Bimmr** [comment]
Ah, looks like something broke in the Lightbow gun file. Gimmie 1 minutes and I'll update the release file

**Comment by Bimmr** [comment]
The release file has been updated: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/releases/tag/Buffer

**Comment by Gr1mmCrypt** [comment]
Dude, you are awesome! Thank you for the help!
