### ISSUE TITLE
Buffer Bow options are bugged

### ISSUE THREAD

**Issue by Adeylis** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#39]
I believe there's a bug when trying to use the bow buffer. This doesn't happen in training mode however, but when going into quests all of the bow options listed, level charge, bolt boost, and H.Draw don't work.

![Bug](https://user-images.githubusercontent.com/109923599/180938878-77df674a-e168-4c0c-a19f-1ad4a435f0c2.PNG)

Here's a Screenshot of the script runner and debug menu as I was testing.

I am using the new build you uploaded today as well another note is, inf stamina on your buffer doesn't stay checked upon restart of game. Not sure if it's intentional but from previous builds it stayed checked.

**Comment by Bimmr** [comment]
Just updated the release with a version that should fix the bow charge level issue. Which may have been causing the others to not work. I'll take a look into why the stamina isn't saving state.

**Comment by Bimmr** [comment]
Stamina not saving is fixed: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/e956dad397a1148ba5e95c04495d0b8f36b36055 Looks like it was all the buffs in the Character section
