### ISSUE TITLE
damage and defense modifiers not working

### ISSUE THREAD

**Issue by Groot0075** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#42]
for some reason, both the damage and defense modifier is not working as it should be and I tried sliding the bar back to 0 before putting back at max for both damage and defence, and it's still not working and no idea why and I am using the latest version

**Comment by Bimmr** [comment]
They're working for me
![image](https://user-images.githubusercontent.com/5053870/181093961-51eeb4fd-77bd-43c0-ae86-cac6ce8d40e4.png)
![image](https://user-images.githubusercontent.com/5053870/181094005-55252ade-01d6-4833-8056-acc78ef077a5.png)

**Comment by Groot0075** [comment]
hmmm strange cause its not working for me what so ever and i been messing with the sliders all day

**Comment by Bimmr** [comment]
What other mods do you have? And did you have any other buffs active that might affect your attack/defence(Not mod related, such as demon drugs)?

**Comment by Groot0075** [comment]
only other mod i have on was the spirit bird mod and that one still works just and don't have any buff's on that would affect damage or attack 
I main as a gunlance user and I have every box checked and before I updated everything was working just fine but after updating the attack and defense modifier in the buffer mod stop working

**Comment by AndarielFrost** [comment]
First of all, sry for my english

I think I know where the problem is.
have the same problem, all works fine, until i hit some mob, then both modifiers (deff-atk) stop working.

i try to delete some mods etc etc, maybe some one takes conflict with this one, buffer mod.
but no, all its ok with all mods runing together.

then finaly trying options in the new buffer, the part in :
Modifiers & Settings --> Character --> Health Options
*Max Dragonheart health
*Max Heroics Health
*Max Adrenaline Health

i think is bugged, cuz when active this ones, the (atk-deff) modifiers goin off and stop working.
and when uncheck that *Max's buffs, (atk-deff) modifiers work again.

thats all i know for now, dont know if have some bug more.

Anyways, rly good work on this mod and thx for do it ^^ 

![Sin título](https://user-images.githubusercontent.com/42504190/181107006-3a2a4890-e3ea-4308-a8fc-751cd7fe69df.jpg)

**Comment by Groot0075** [comment]
wait really huh didin't the health options would bug out the attack and defense modifier

**Comment by Bimmr** [comment]
The way I do the attack and defence modifier is kinda sneaky. I add a custom atk and def value to an existing buff so that way the game applies the buff for me. Might be that the health buffs use the fields I used

**Comment by Groot0075** [comment]
it's very possible as I tested the modifiers without the max health for dragon heart, adrenaline, and heroics options and everything worked as it should be

**Comment by Bimmr** [comment]
Just tested with Dragonheart, Heroics and Adrenaline all active and the stat modifiers are still working for me
![image](https://user-images.githubusercontent.com/5053870/181143547-30ff2ab7-3312-4c45-ada2-32cc67acbeec.png)

**Comment by Bimmr** [comment]
What level of DragonHeart did you have active?

And for it to break for some people but not others just means there's some condition we haven't found that's causing it to break

**Comment by Bimmr** [comment]
Also, are you setting the attack modifier before or after activating the dragon heart.

**Comment by Groot0075** [comment]
I don't know as I have no idea where to check the dragon heart level all I know is when I had it enabled it messed with the modifiers for defense and attack

also, I do believe had dragon heart enabled before the attack and defense modifier if I remember correctly but I have a terrible memory so I could be wrong on that

**Comment by Bimmr** [comment]
Looks like it may be an issue if you enable DragonHeart Health without actually having the skill equipped

**Comment by Groot0075** [comment]
weird but would make sense I guess just never would think that it would cause issues with dragon heart equipped  
at least I didn't think that was possible

**Comment by Bimmr** [comment]
Yup, that's the issue. If you had DragonHeart enabled, but it couldn't find the skill it would just skip the rest of the buffs in Character.

I'll try and get a fix uploaded tomorrow.

**Comment by Groot0075** [comment]
okie dokie thank for helping out with this

**Comment by Bimmr** [comment]
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/7c8f1c82989c169853231533cc3b66b409a0562f Turns out the fix was fast. I've updated the release file here but will upload it to Nexus tomorrow.

**Comment by Groot0075** [comment]
okie dokie  and again thank you for taking the time to look into this
