### ISSUE TITLE
IG bug?

### ISSUE THREAD

**Issue by daiyaaa** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#43]
# Describe the bug
<IG's hunting bug extract is no longer permanent
Also, the persistence of hunting bug stamina is now expired.>

# Screenshots

# Additional context

**Comment by Bimmr** [comment]
I did notice issues in the code that was stopping the white and orange extract from being permanent. But I'll have to go into the game to test the red, and kinsect stamina

**Comment by Bimmr** [comment]
Fixed Insect Glaive. https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/302c49c4c072c102a5fc277dfb920d57258b1149

I've updated the release file here, and will upload to Nexus tomorrow.
