### ISSUE TITLE
Add Stun, Paralysis and Spider Web

### ISSUE THREAD

**Issue by daiyaaa** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#45]
# Describe the bug
<I'm disabling the stun, but it's still triggered.>

# Screenshots

# Additional context

**Comment by Bimmr** [comment]
You'll still get the effect, but you'll be able to move right after. It's the same reason I don't have paralysis yet.

**Comment by daiyaaa** [comment]
Thank you.
You got it.

**Comment by Bimmr** [comment]
For now, I've removed Stun and added it to the list of Paralysis and Spider Web that I need to look into removing the effect

**Comment by Bimmr** [comment]
I've re-added them, but just added a tooltip saying that the visual effect will still happen. Eventually, I'll try and see if I can find a way to stop that without stopping the whole hit animation. but for now it's not something I'm looking into. https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/7bd2d60e073428219cbbc86159cb87a3a37ccd47
