### ISSUE TITLE
May be add a weapon affinity changer .lau

### ISSUE THREAD

**Issue by DDOLDD** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#46]
# Is your feature request related to a problem? Please describe.
hate to not being able to crit every hit
okQAQ

# Describe the solution you'd like
being able to change the weapon affinity
 to 20 50 or 100
# Additional context

**Comment by Bimmr** [comment]
Duplicate https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/issues/33
