### ISSUE TITLE
Maybe Unicode is not supported. Korean output is broken.

### ISSUE THREAD

**Issue by calycekr** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#49]
![image](https://user-images.githubusercontent.com/4094424/184442733-5db424cb-d11b-4d8b-bffc-d195c34cca62.png)

**Comment by Bimmr** [comment]
Looks like I have a version in testing that works. I had to change the font to use a font type that supports more languages.
I'll have a few extra items I'll need to be translated to make sure everything is customizable. 
![image](https://user-images.githubusercontent.com/5053870/184466166-5052af94-9d35-4fdf-ae9c-fb34fdeb563c.png)

**Comment by Bimmr** [comment]
```JSON
    "window":{
        "title": "Modifiers & Settings",
        "settings": {
            "title": "Settings",
            "language": "Language"
        },
        "about":{
            "author": "Author",
            "version": "Version"
        }
    },
```

**Comment by Bimmr** [comment]
```JSON
 "window":{
        "toggle_button": "Toggle Buffer GUI",
        "title": "Modifiers & Settings",
        "settings": "Settings",
        "language": "Language",
        "font_size": "Font Size",
        "font_size_apply": "Apply",
        "about": "About",
        "author": "Author",
        "version": "Version"
    },
```
Are more translations that are needed, I'm pushing to Github right now so you can create another PR if you want.

**Comment by calycekr** [comment]
Thank you @Bimmr
