### ISSUE TITLE
Is it possible to add exhausted and mind eye effects to attacks?

### ISSUE THREAD

**Issue by 931705126** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#51]
# Is your feature request related to a problem? Please describe.

# Describe the solution you'd like

# Additional context

**Comment by Bimmr** [comment]
I will not be making any changes/edits to skills, changing activation of skills, or enabling skills. I also don't plan to modify the status effects on weapons.

To me, changing those would remove the whole point of creating a build to get those skills or effects
