### ISSUE TITLE
Translation Needed - ko_kr

### ISSUE THREAD

**Issue by Bimmr** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#52]
A new buff is being added; The spinning axe buff: https://game8.co/games/Monster-Hunter-Rise/archives/315895#hm_16
Tagging @calycekr In case you want to do translations

````JSON
"chainsaw_buff": "Chainsaw Buff"
````

**Comment by calycekr** [comment]
@Bimmr Ok, I'll do it.

**Comment by Bimmr** [comment]
Thanks
