### ISSUE TITLE
HeavyBowgun language.get

### ISSUE THREAD

**Issue by Chikaze** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#53]
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/0835abb5b19ed0a9c4c18323eac583626cc022d7/Buffer/autorun/Buffer/Modules/HeavyBowgun.lua#L58

        changed, data.charge_level = imgui.slider_int(language.get(languagePrefix .. "charge_level"), data.charge_level, -1, 3, data.charge_level > -1 and
        language.get(languagePrefix .. "charge_level_prefix") .. " %d" or language.get(languagePrefix .. "charge_level_disabled"))

**Comment by Bimmr** [comment]
Looks like I missed this one. Thanks.
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/ddd08e50793f7b1bd49986840a4177a2ddcafe5a
