### ISSUE TITLE
SChinese and TChinese language files

### ISSUE THREAD

**Issue by Chikaze** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#54]
[zh-cn.zip](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/files/9379008/zh-cn.zip)
[zh-tw.zip](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/files/9379020/zh-tw.zip)

[NotoSansSC-Bold.otf] MHR Overlay2.0+ Contains this font file
[zh-tw] In order for zh-hant to display text normally, font file still uses "NotoSansSC-Bold.otf"

**Comment by Chikaze** [comment]
[NotoSansSC-Bold.zip](https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/files/9379241/NotoSansSC-Bold.zip)

**Comment by Bimmr** [comment]
Thanks, I've got them added https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/f713b982d993650f31ec29fed30cf203387d4218.

Looks like the only thing missing is:
The spinning axe buff: https://game8.co/games/Monster-Hunter-Rise/archives/315895#hm_16
````JSON
"chainsaw_buff": "Chainsaw Buff"
````

**Comment by Chikaze** [comment]
you are welcome, thank you too!

----
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/34ece107e55a2fab04527d1d6ca47cfef83584e9/Buffer/data/Buffer/Languages/zh-cn.json#L178
```json
"chainsaw_buff": "斧属性强化"
```

-----
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/34ece107e55a2fab04527d1d6ca47cfef83584e9/Buffer/data/Buffer/Languages/zh-tw.json#L178
```json
"chainsaw_buff": "斧屬性強化"
```
