### ISSUE TITLE
Use Kor n error occurred in the file Languages.lua

### ISSUE THREAD

**Issue by asksn0w** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#58]
# Describe the bug
When I launch the game 
Alerts errorscreen to running Buffer mod 

How can i resolve it?

# Screenshots

ScriptRunner Message
---------------------------
sol: runtime error: ...rHunterRise\reframework\autorun/Buffer\Misc\Language.lua:30: attempt to index a nil value (field '?')
stack traceback:
	...rHunterRise\reframework\autorun/Buffer\Misc\Language.lua:30: in function 'Buffer.Misc.Language.change'
	...rHunterRise\reframework\autorun/Buffer\Misc\Language.lua:19: in function 'Buffer.Misc.Language.init'
	...\common\MonsterHunterRise\reframework\autorun\Buffer.lua:34: in main chunk

# Additional context

**Comment by ROBOTIC-HANDS** [comment]
I am having the same issue

**Comment by asksn0w** [comment]
The cause was Install this mod with Nexusmod's Vortex
Vortex make symbolic link 'data\Buffer\Languages\*.json' files 
So, i copy data\Buffer\Languages\*.json to reframework folder
