### ISSUE TITLE
It occurs an error in Chinese language version(zh_cn).Could you please fix it？Thank you.

### ISSUE THREAD

**Issue by skyBing** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#59]
I have some questions for Chinese language version. It occurs an error when I use the Character(角色) function in Chinese language(zh-cn),. The function is prevent Conditions, Blights, Alimemts(异常状态抗性), for example, sleep(睡眠). But it doesn't happen in English language version. Can you fix it? Thank you.
There is the error:
Last Script Error.
Attempted to set invalid REManagedObject field: < SleepMovableTimer>k_ BackingFieldstack traceback:...terRise\reframework\autorun/BufferModules\Character.lua:158?in function <..terRise\reframework\autorun/BufferModules\Character.lua:51>

**Comment by skyBing** [comment]
我确定就是在N站下载的版本，使用的是zh-cn，我问题中提到的翻译只是为了说明举例是用什么功能会报错，想刚才我去测试了以下， 猎人状态>累加类异常>火属性 还是有问题
![屏幕截图 2022-08-20 230629](https://user-images.githubusercontent.com/111642302/185754280-6fdefac2-2717-4446-a339-b9d66f90f158.png)

> [](url)

**Comment by skyBing** [comment]
我所有的mod中只有buffer mod有这个问题，而且这个mod已经从曙光更新后的那个版本就存在了，那时候没有中文版，我自己汉化的版本中就有这个问题，后来的每次mod更新我都会进行汉化，这个问题一直存在，最新版本中内置的中文版还是存在这个问题

**Comment by Bimmr** [comment]
I'm away for the next week and will be back on Aug 28th. So there will be no updates till then

**Comment by skyBing** [comment]
I come back. I uninstall the game, the reframework and all the mods. Then I install the game, the latest reframework and the latest buffer mod from nexusmods. The error is still alive in Chinese Version. But it is also alive in English version. Here are the error pictures. Even I change another clear computer, it is also alive. I ask two friends to try the mod. They also have this problem. I open the reframework crash file(reframework_crash.dmp). The picture is below. 
![屏幕截图 2022-08-21 093324](https://user-images.githubusercontent.com/111642302/185772254-9cbc3121-fe42-4abe-a5ec-3aab6df4d160.png)
![屏幕截图 2022-08-21 093401](https://user-images.githubusercontent.com/111642302/185772257-ae0aae1b-caa1-478f-9151-bff1bfb0ac05.png)
![屏幕截图 2022-08-21 095626](https://user-images.githubusercontent.com/111642302/185772260-56dc0a7b-34eb-447e-821a-f7ea6537431b.png)

**Comment by skyBing** [comment]
Here are reframework logs when the error occurs:
[2022-08-21 10:14:45.764] [REFramework] [error] Attempted to set invalid REManagedObject field:_FireLDurationTimer
stack traceback:
	...terRise\reframework\autorun/Buffer\Modules\Character.lua:114: in function <...terRise\reframework\autorun/Buffer\Modules\Character.lua:52>
[2022-08-21 10:14:45.764] [REFramework] [error] Attempted to set invalid REManagedObject field:_FireDamageTimer
stack traceback:
	...terRise\reframework\autorun/Buffer\Modules\Character.lua:115: in function <...terRise\reframework\autorun/Buffer\Modules\Character.lua:52>
![屏幕截图 2022-08-21 101743](https://user-images.githubusercontent.com/111642302/185772499-caa83b68-1c3f-4988-a25e-6aea9400354a.png)

**Comment by skyBing** [comment]
It only occurs error when I use the function ( prevent Conditions, Blights, Alimemts ). When I use other functions, it works good.

**Comment by Bimmr** [comment]
Maybe something changed in the latest free title update or the game uses
different fields for that stuff since it's a different region? I'll
check it out next week.

**Comment by Bimmr** [comment]
Could also be an error that only happens when you're not in a quest

**Comment by skyBing** [comment]
Sorry. I understand wrong. It isn't an error. It works good when I'm in a quest.  When I'm not in a quest, I try the function and the error appears. It's my question, not yours. I'm sorry to bother you. This issus could be closed.

**Comment by Bimmr** [comment]
Note to myself when updating code tomorrow:

> Make sure the player isn't in the lobby when preventing status otherwise errors occur

**Comment by Bimmr** [comment]
Fixed by checking if the player is in a quest before trying to set conditions: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/7bd2d60e073428219cbbc86159cb87a3a37ccd47
