### ISSUE TITLE
infinite wyvernheart does not work

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#60]
# Describe the bug
wyvernheart not only empties as normal, it recharges just as slowly as if there was no mod.

**Comment by Bimmr** [comment]
Looks like I missed something when renaming variables:

Note to tomorrow me: 
> https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/main/Buffer/autorun/Buffer/Modules/HeavyBowgun.lua#L42 
>` if data.wyvern_machinegun then`
> Needs to be changed to  
> `if data.wyvern_machine_gun then`

**Comment by Bimmr** [comment]
Fixed https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/f2436bea001823fb3d97890a5e1e9e6a3a033c13
