### ISSUE TITLE
multiply raw damage

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#61]
# Describe the solution you'd like
Add a way to change raw damage manipulatively rather than just setting a total value.

# Additional context
this way weapons will still have differences when using the feature.

**Comment by Bimmr** [comment]
With the way I'm changing the attack and defense this isn't something that is possible at the moment. I'm actively looking for new ways to manipulate the attack and defense without having to overwrite each weapon's stats, but so far no luck.
