### ISSUE TITLE
add elemental damage / shell damage modifier.

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#62]
# Describe the solution you'd like
Add support for setting elemental value and gunlance damage modifiers, as neither scale with raw.

**Comment by Bimmr** [comment]
I've seen values in the weapons that I can change to do this, I just haven't tested if changing them will work yet

**Comment by NIGELTEAPOT** [comment]
Alright, thanks!  I personally tried editing some bowgun values in the game files but they don't seem to work, but I'm sure you ccan do better than I can.

**Comment by Bimmr** [comment]
In regards to the gunlance damage modifiers, I'm not sure if you mean shelling level or type, but I don't think I'm gonna touch those.
