### ISSUE TITLE
remove hitstop/hitlag

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#63]
# Describe the solution you'd like
An older mod used to remove hitstop/lag, and there is a working one for world, but none for sunbreak.

# Additional context
In base rise, apparently hitstop/lag was universally controlled from a value in line/slot 27 of whatever relevant file according to the outdated mod creator back in February.

**Comment by Bimmr** [comment]
Do you mean just prevent your character from stumbling when hit? Not too sure what hitstop is and there is nothing I can do to prevent lag

**Comment by NIGELTEAPOT** [comment]
Hitstop or hitlag is when the game stops or slows down to "sell" a hit or make it so your character is animation locked after an ability to make you easier to hit.  It's determined by some line in the code, but all the other mods that change it are LONG outdated.

It's supposed to give "weight" to animations, but it makes the game much easier without it as you no longer have to "overcommit" to each action.

**Comment by Bimmr** [comment]
Added no knockback with Hyper Armor which is probably the only way I'd be adding this https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/3a3fcb154e2253363df1eafa11593ac0f5c5caa9
