### ISSUE TITLE
Remove/change recoil for bowguns as well adding rapid fire to all shots.

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#64]
# Describe the solution you'd like
Set values for removal/changing recoil and reload speed for bowguns as well as shot type.

# Additional context
In iceborne it was relatively easy to make a mod to remove reloading (which you have done already) but also change all recoil AND shot type.

This is because semi-auto, rapid, auto-reload single, wyvern ammo, and mortar shots were tied to recoil speed / recoil type and not their own values.  Nearly every bowgun value is based on one table in one file, and all others reference different values in it.

Every bullet had one of 36 recoil preset picked from a list, and every gun had a unique shell id.

shell ID
![gun file](https://user-images.githubusercontent.com/111661379/185766178-512fd839-bc8c-4ea1-9653-5381e9cae304.JPG)

All you had to do is mod just one shell id to whatever you wanted (say, 5 shots of every ammo type, or even 10) and set the recoil preset in said shot id for each shot type to the same one.
![shell id](https://user-images.githubusercontent.com/111661379/185766210-7f514346-23d6-4885-afcb-73bd19216f35.JPG)

Then you go into the recoil preset table and set your chosen preset to all "rapid 1" for all levels of recoil modifier, which would make every shot type have no recoil at all but also rapid fire.
![recoil preset](https://user-images.githubusercontent.com/111661379/185766212-6e1b9b0e-50c7-40a3-8e8a-3495246789f8.JPG)

All you would have to do then is change the shell id of every gun to the same using a batch edit, and every gun in the game not only would have rapid fire ammo but also as many shot types with as many bullets as you want AND no recoil.

Since you have already fixed the problem of needing to reload, and if rise is structured similar to world, you would only really need to make it so every gun can use every shot type (which was just a simple id change in a table in world after modding just one shell id), and then change every shot type in one shell id to one recoil preset

**Comment by Bimmr** [comment]
I should just be able to re-purpose the code for no deviation to work for recoil. However, I'm not sure about reload speed yet; I'll need to take a look.

The issue I have is that I want to be able to turn things off as well. If it was just a click the button to set and then you need to restart your game to turn it off a lot of this would be significantly easier. (For example, I have code that will unlock all dangos, but I can't get it to de-activate so it's not in the mod yet)

**Comment by NIGELTEAPOT** [comment]
Oh I see.  I found one of the files in the .pak that was the shell values, but they way the files are structured is completely different to how world had it and make reference to files I can't find.

**Comment by Bimmr** [comment]
I've added a no-recoil https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/cd9ca3f89f61c22ebb77fd4cd7f4d841a955fd34, but I probably won't be adding rapid shot as you can make it so you have unlimited ammo and auto-reload.
