### ISSUE TITLE
surge slash combo breaks with static charge level setting

### ISSUE THREAD

**Issue by NIGELTEAPOT** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#65]
# Describe the bug
surge slash combo breaks with static charge level setting, charge level setting doesn't matter.  tested on training dummy and monster and both are consistent.

having written this out, it's very confusing without context.  so I will refer to each stage of the three-hit combo by 1-3, and the button by its switch controller name (x would be triangle, a would be circle).  therefore the x combo will be called x1 x2 x3.

falling slash:
- x1, x2 are fine no matter what, with a complete x combo or mixing and matching.  x3 does not work in any case, the weapon just clips through the monster with no damage or hit notification.

vortex slash:
- a1, a2 works always; though the hitbox of the second hit of a2 seems much smaller with static charge level.  a3 is always broken with the first hit connecting but the second never registering.

rising slash:
- there is no problem with the x+a combo.

turning off the static charge level makes everything go back to normal.

power sheathe on or off does not affect the bug.

**Comment by Bimmr** [comment]
Pretty sure this is the same thing as this: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/issues/18. If it is, then there is nothing I can do as Monster Hunter Rise stops it from connecting

**Comment by NIGELTEAPOT** [comment]
Oh, ok.  I understand!
