### ISSUE TITLE
Fix issue with Sharpness

### ISSUE THREAD

**Issue by Bimmr** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#7]
With new purple sharpness, it's downgrading them to white, but everything else to purple?

**Comment by jacky50403** [comment]
purple sharpness seems not working

**Comment by Phokust** [comment]
The purple sharpness seems to work on my side, the weapon's sharpness can be seen going down from purple to white to blue, etc. however, the outer color that indicates the weapon's sharpness remains purple.

**Comment by Bimmr** [comment]
Looks like the previous fix works - closing ticket
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/c17178f62f88abb8780166970e900a361b583ff2
