### ISSUE TITLE
Canteen 100% with ticket bug

### ISSUE THREAD

**Issue by Aisaka3574** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#79]
All canteen dango become 100% with or without a ticket permenantly after one use of dango, and requires a full game restart to reset it.

**Comment by Bimmr** [comment]
Fixed: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/bcec03781a2970c727015cd7ce6aa564a749ccd1

Will upload to nexus once I finish the bindings.
