### ISSUE TITLE
Value type is not changed

### ISSUE THREAD

**Issue by Chikaze** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#80]
Value type is not changed when I change 'modification' from Number type to Boolean type.

https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/61c46b97d5bfcc9529f7986c07ea18d49f164bf9/Buffer/autorun/Buffer/Misc/Bindings.lua#L268

**Comment by Bimmr** [comment]
Fixed https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/2996de6f6451d6e0bf5321c388f49c554deb2990
