### ISSUE TITLE
missing placeholders in ko-kr.json

### ISSUE THREAD

**Issue by Chikaze** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#84]
### 1
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/c53eea9318a43debcf11e007423b5eda0f2437c3/Buffer/data/Buffer/Languages/ko-kr.json#L64

                "stun": "Stun",
                "stun_tooltip": "The visual effect will still play",
                "paralyze": "Paralyze",
                "paralyze_tooltip": "The visual effect will still play",
                "thread": "Thread",
                "thread_tooltip": "The visual effect will still play"
            }

-----
### 2
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/c53eea9318a43debcf11e007423b5eda0f2437c3/Buffer/data/Buffer/Languages/ko-kr.json#L85

            "defence_tooltip": "만약 스탯이 깨지면 슬라이더를 왼쪽으로 드래그하여 재설정",
            "affinity": "Affinity",
            "affinity_disabled": "Off",
            "affinity_tooltip": "Drag slider to the left to reset if the stat breaks"
        },

-----
### 3
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/c53eea9318a43debcf11e007423b5eda0f2437c3/Buffer/data/Buffer/Languages/ko-kr.json#L114
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/c53eea9318a43debcf11e007423b5eda0f2437c3/Buffer/data/Buffer/Languages/ko-kr.json#L136
https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/c53eea9318a43debcf11e007423b5eda0f2437c3/Buffer/data/Buffer/Languages/ko-kr.json#L150

        "no_recoil": "No Recoil*****"

**Comment by Bimmr** [comment]
Temporary fix. https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/8d9bee0e7de240dd27b4d1f85226cd5dc17e34b7
