### ISSUE TITLE
More messages added to language file

### ISSUE THREAD

**Issue by Bimmr** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#87]
Sorry... I know I said I was done but I thought having a nice message popup when you enabled/disabled a binding would be helpful:
![image](https://user-images.githubusercontent.com/5053870/192799170-d9220f3f-22be-4c54-9faf-8f74622dcd1a.png)

https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/blob/ec904eaade911ffaeddc1a16a765b4c1b5c9b55c/Buffer/data/Buffer/Languages/en-us.json#L29-L30

@Gentechnik
@Chikaze

**Comment by Gentechnik** [comment]
no problem, can do, I try to help where I can
