### ISSUE TITLE
Add max intrepid heart bar

### ISSUE THREAD

**Issue by christensennn** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#91]
# Describe the solution you'd like

Hello sir, could you add a function for max intrepid heart bar(a new skill released in the newest version)? I think it's more interesting than just lock the health bar. Thank you.

**Comment by Bimmr** [comment]
Turns out I may add this https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/9120ccb64afeced29dd6709c4d51ae3211ef7ae3
