### ISSUE TITLE
Greatsword Falling Slash doesn't register hits

### ISSUE THREAD

**Issue by legendppk** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#93]
# Describe the bug
When using this mod's buff slider on Greatsword to charge level 1, 2, or 3, Falling Slash move sets (from the Surge Slash Combo move sets) don't register has hits and pass through the target harmlessly.

On Charge lvl 1: Falling Slash I, II, and III all fail to register their hits
On Charge lvl 2: Falling Slash III fails to register as a hit
On Charge lvl 3: Falling Slash III fails to register as a hit
On Charge lvl 0 or Off: All Falling Slash I, II, and III registers their hits like normal

# Screenshots

# Additional context
Tested on dummy and on actual monsters. Tested with different swords.

**Comment by Bimmr** [comment]
Monster hunter prevents the charged hits from hitting. Nothing I can do: https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/issues/18
