### ISSUE TITLE
[Feature]: increase buff duration

### ISSUE THREAD

**Issue by Knovic4ever** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#95]
### Which mod is this report for:

Buffer

### Is your feature request related to a problem? Please describe.

I know buff duration mod already posted on nexus but it doesn't work for gamepass version.

### Describe the solution you'd like

It would be nice there's a feature to increase the buff duration like seeds, juice and powders.

**Comment by Bimmr** [comment]
Sorry, that's not something I'm likely to add to this mod.
