### ISSUE TITLE
[Feature]: Add Counter Charger for HBG

### ISSUE THREAD

**Issue by HasturQ** [Bimmr/Monster-Hunter-Rise-Reframework-Scripts-#96]
### Which mod is this report for:

Buffer

### Is your feature request related to a problem? Please describe.

1. for HBG: add the buff after Counter Charger
2. add one option for max_dragonheart: set vital not bigger than newHealth, instead of fix the vital = math.min(max, newHealth)

### Describe the solution you'd like

1. emm, may be "managed:set_field()"?
2.  if player's vital > newHealth, then playerData:set_field("_r_Vital", math.min(max, newHealth) + .0)

**Comment by Bimmr** [comment]
I'll take a look at adding [Counter Charger](https://game8.co/games/Monster-Hunter-Rise/archives/315899#hm_14), as for the second thing I'm not sure what you're asking.

**Comment by HasturQ** [comment]
I mean, when you have dragonheart Lv.5, your health will **not be higher than** 0.8 \* max, instead of being fixed as 0.8 \* max.
Thanks a lot.

**Comment by Bimmr** [comment]
Ah, ok. I've created a separate ticket for that https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/issues/98

**Comment by Bimmr** [comment]
Added in https://github.com/Bimmr/Monster-Hunter-Rise-Reframework-Scripts-/commit/27b07bee39f93c1eeafccf045e51f7966571cca0
